function word=dbletters(word,index)

switch(index)
            case 1
                word=[word 'A'];
            case 2
                word=[word 'B'];
            case 3
                word=[word 'C'];
            case 4
                word=[word 'D'];
            case 5
                word=[word 'E'];
            case 6
                word=[word 'F'];
            case 7
                word=[word 'G'];
            case 8
                word=[word 'H'];
            case 9
                word=[word 'I'];
            case 10
                word=[word 'J'];
            case 11
                word=[word 'K'];
            case 12
                word=[word 'L'];
            case 13
                word=[word 'M'];
            case 14
                word=[word 'N'];
            case 15
                word=[word 'O'];
            case 16
                word=[word 'P'];
            case 17
                word=[word 'Q'];
            case 18
                word=[word 'R'];
            case 19
                word=[word 'S'];
            case 20
                word=[word 'T'];
            case 21
                word=[word 'U'];
            case 22
                word=[word 'V'];
            case 23
                word=[word 'W'];
            case 24
                word=[word 'X'];
            case 25
                word=[word 'Y'];
            case 26
                word=[word 'Z'];
            
            case 27
                word=[word 'a'];
            case 28
                word=[word 'b'];
            case 29
                word=[word 'c'];
            case 30
                word=[word 'd'];
            case 31
                word=[word 'e'];
            case 32
                word=[word 'f'];
            case 33
                word=[word 'g'];
            case 34
                word=[word 'h'];
            case 35
                word=[word 'i'];
            case 36
                word=[word 'j'];
            case 37
                word=[word 'k'];
            case 38
                word=[word 'l'];
            case 39
                word=[word 'm'];
            case 40
                word=[word 'n'];
            case 41
                word=[word 'o'];
            case 42
                word=[word 'p'];
            case 43
                word=[word 'q'];
            case 44
                word=[word 'r'];
            case 45
                word=[word 's'];
            case 46
                word=[word 't'];
            case 47
                word=[word 'u'];
            case 48
                word=[word 'v'];
            case 49
                word=[word 'w'];
            case 50
                word=[word 'x'];
            case 51
                word=[word 'y'];
            case 52
                word=[word 'z'];
                case 53
                word=[word 'T'];
            case 54
                word=[word 'H'];
            case 55
                word=[word 'E'];
            case 56
                word=[word 'R'];
            case 57
                word=[word 'E'];
            case 58
                word=[word 'I'];
            case 59
                word=[word 'S'];
            case 60
                word=[word 'N'];
            case 61
                word=[word 'O'];
          
                
            otherwise
                word=[word ' *'];
end